version: '3.8'

services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://admin:root@db:3306/test_db
      - ACCESS_TOKEN_SECRET=aSDZfRrMMFz7qS82A8peEBAOZV9Bzx0n
      - BASE_PATH=/app
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db-data:/var/lib/mysql

volumes:
  db-data: